Repository tryber/sd-010-a-project-delivery-app, pull requests merged in 2021-11, with the labels that each got.

#19 Main Group 11 sequelize
  README.md
  back-end/package-lock.json
  back-end/package.json
  back-end/src/api/app.js
  back-end/src/api/server.js
  back-end/src/database/migrations/.gitkeep
  back-end/src/database/migrations/20211109162427-create-user.js
  back-end/src/database/migrations/20211109162540-create-sale.js
  back-end/src/database/migrations/20211109162552-create-product.js
  back-end/src/database/migrations/20211109162620-create-products-sale.js
  back-end/src/database/models/index.js
  back-end/src/database/models/product.js
  back-end/src/database/models/productsSale.js
  back-end/src/database/models/sale.js
  back-end/src/database/models/user.js
  back-end/src/database/seeders/.gitkeep
  back-end/src/database/seeders/20211109174234-seed-users.js
  back-end/src/database/seeders/20211109174319-seed-products.js
Labels: group-11

#27 Main group 8 back feat sequelize setup
  README.md
  back-end/src/database/migrations/20211109211240-users.js
  back-end/src/database/migrations/20211109211642-sales.js
  back-end/src/database/migrations/20211109212050-products.js
  back-end/src/database/migrations/20211109212352-salesProducts.js
  back-end/src/database/models/product.js
  back-end/src/database/models/sale.js
  back-end/src/database/models/saleProduct.js
  back-end/src/database/models/user.js
  back-end/src/database/seeders/20211109220036-Users.js
  back-end/src/database/seeders/20211109221215-Products.js
  package-lock.json
Labels: group-8

#39 EndPoint Login
  back-end/.env.example
  back-end/jwt.evaluation.key
  back-end/src/api/app.js
  back-end/src/controllers/index.js
  back-end/src/controllers/userController.js
  back-end/src/database/models/salesProducts.js
  back-end/src/routers/index.js
  back-end/src/routers/loginRouter.js
  back-end/src/services/index.js
  back-end/src/services/userService.js
  back-end/src/utils/errorMap.js
  back-end/src/utils/statusCodeMap.js
  front-end/src/styles/form.css
Labels: code review

#50 [MAIN GROUP 4] [FEAT] [CONTEXT API] [LOGIN CONTEXT API]
  front-end/package-lock.json
  front-end/src/context/LoginContext.js
  front-end/src/context/index.js
  front-end/src/index.js
  front-end/src/provider/LoginProvider.js
Labels: code review

#53 [Main group 13] - Get All Products
  back-end/src/api/app.js
  back-end/src/controllers/index.js
  back-end/src/controllers/productController.js
  back-end/src/database/models/products.js
  back-end/src/routers/index.js
  back-end/src/routers/productRouter.js
  back-end/src/services/index.js
  back-end/src/services/productService.js
  back-end/src/utils/errorMap.js
Labels: code review

#36 [GRUPO 19] routes
  front-end/src/Components/Routes.jsx
  package-lock.json
  package.json
Labels: group-19

#25 Main group 3 back-end login
  back-end/src/api/app.js
  back-end/src/api/auth/encriptation.js
  back-end/src/api/auth/validateToken.js
  back-end/src/api/controllers/index.js
  back-end/src/api/controllers/userController.js
  back-end/src/api/messages/errorMessages.js
  back-end/src/api/middleware/index.js
  back-end/src/api/services/index.js
  back-end/src/api/services/userService.js
  back-end/src/database/models/products.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/salesproducts.js
  back-end/src/database/models/user.js
  back-end/src/database/seeders/20211109203203-users.js
  back-end/src/database/seeders/20211109204407-products.js
  back-end/src/tests/login.test.js
Labels: group-03

#73 [ Main Group 16 ] feat: initial config redux
  front-end/src/index.js
  front-end/src/redux/actions/index.js
  front-end/src/redux/reducers/index.js
  front-end/src/redux/slices/userSlice.js
  front-end/src/redux/store/index.js
  package-lock.json
  package.json
Labels: grupo-16

#59 [Main Group 16] Backend initial setup
  back-end/jwt.evaluation.key
  back-end/package.json
  back-end/src/api/app.js
  back-end/src/api/controllers/userController.js
  back-end/src/api/middlewares/errorHandler.js
  back-end/src/api/services/userService.js
  back-end/src/api/utils/AppError.js
  back-end/src/database/migrations/20211109190926-create-users.js
  back-end/src/database/models/productSale.js
  back-end/src/database/models/products.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/users.js
  front-end/package-lock.json
  front-end/package.json
  package-lock.json
  package.json
Labels: grupo-16

#55 feat: sequelize inicialization
  back-end/src/database/migrations/20211110174045-create-users.js
  back-end/src/database/migrations/20211110174423-create-sales.js
  back-end/src/database/migrations/20211110174601-create-products.js
  back-end/src/database/migrations/20211110174745-create-sales-products.js
  back-end/src/database/models/products.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/sales_products.js
  back-end/src/database/models/users.js
  back-end/src/database/seeders/20211110190345-users.js
  back-end/src/database/seeders/20211110191325-products.js
  package-lock.json
Labels: group-14

#70 [ Main group 3 ] - login/register
  README.md
  back-end/.env.example
  back-end/src/api/app.js
  back-end/src/api/controllers/userController.js
  back-end/src/api/messages/errorMessages.js
  back-end/src/api/middleware/validateNewUser.js
  back-end/src/api/services/userService.js
Labels: group-03

#75 feat: login
  back-end/src/api/server.js
  back-end/src/controllers/user.js
  back-end/src/database/models/sale.js
  back-end/src/index.js
  back-end/src/models/User.js
  back-end/src/services/User.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/pages/Login.js
Labels: group-8

#99 Main group 8 products
  back-end/src/api/server.js
  back-end/src/controllers/Products.js
  back-end/src/database/models/product.js
  back-end/src/models/Products.js
  back-end/src/services/Products.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/pages/Login.js
Labels: group-8

#98 Main group 3 db refact
  back-end/src/database/migrations/20211109180427-create-user.js
  back-end/src/database/migrations/20211109184609-create-products.js
  back-end/src/database/migrations/20211109185711-create-sales.js
  back-end/src/database/migrations/20211109191743-create-sales-products.js
  back-end/src/database/models/products.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/salesproducts.js
  back-end/src/database/models/user.js
  back-end/src/database/seeders/20211109204407-products.js
Labels: group-03

#79 Configuracao do Front End - Pages
  back-end/.env.example
  back-end/package-lock.json
  back-end/package.json
  back-end/src/database/migrations/20211109224249-create-user.js
  back-end/src/database/migrations/20211109224410-create-sale.js
  back-end/src/database/migrations/20211109224442-create-product.js
  back-end/src/database/migrations/20211109224604-create-sales-product.js
  back-end/src/database/models/index.js
  back-end/src/database/models/product.js
  back-end/src/database/models/sale.js
  back-end/src/database/models/sales_product.js
  back-end/src/database/models/user.js
  back-end/src/database/seeders/20211109230615-products.js
  back-end/src/database/seeders/20211109230619-users.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/index.js
  front-end/src/pages/Admin.jsx
  front-end/src/pages/Cadastro.jsx
  front-end/src/pages/CheckoutComprador.jsx
  front-end/src/pages/Login.jsx
  front-end/src/pages/PedidoEspecífico.jsx
  front-end/src/pages/Produtos.jsx
  front-end/src/pages/TodasAsVendas.jsx
  front-end/src/pages/TodosOsPedidos.jsx
  front-end/src/pages/VendaEspecífica.jsx
  front-end/src/pages/notFound.jsx
  front-end/src/routes/Routes.jsx
  package-lock.json
  package.json
Labels: Group-18

#49 🎨 Inicialização - configuração Sequelize
  back-end/.env.example
  back-end/package-lock.json
  back-end/package.json
  back-end/src/database/migrations/20211109224249-create-user.js
  back-end/src/database/migrations/20211109224410-create-sale.js
  back-end/src/database/migrations/20211109224442-create-product.js
  back-end/src/database/migrations/20211109224604-create-sales-product.js
  back-end/src/database/models/index.js
  back-end/src/database/models/product.js
  back-end/src/database/models/sale.js
  back-end/src/database/models/sales_product.js
  back-end/src/database/models/user.js
  back-end/src/database/seeders/20211109230615-products.js
  back-end/src/database/seeders/20211109230619-users.js
  front-end/package-lock.json
  front-end/package.json
  package-lock.json
  package.json
Labels: Group-18

#35 [GRUPO 19] login-page
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/Components/Login.jsx
  front-end/src/Components/Register.jsx
  front-end/src/Components/Routes.jsx
  front-end/src/index.js
Labels: group-19

#41 Main group 11 [fix] sequelize
  back-end/src/api/app.js
  back-end/src/database/migrations/20211109162427-create-user.js
  back-end/src/database/migrations/20211109162540-create-sale.js
  back-end/src/database/migrations/20211109162552-create-product.js
  back-end/src/database/migrations/20211109162620-create-products-sale.js
  back-end/src/database/models/index.js
  back-end/src/database/models/product.js
  back-end/src/database/models/productsSale.js
  back-end/src/database/models/sale.js
  back-end/src/database/models/user.js
  back-end/src/database/schemas/product.js
  back-end/src/database/schemas/productsSale.js
  back-end/src/database/schemas/sale.js
  back-end/src/database/schemas/user.js
  back-end/src/database/seeders/20211109174234-seed-users.js
  back-end/src/database/seeders/20211109174319-seed-products.js
Labels: group-11

#40 [Grupo 10] (Back-end) Sequelize
  back-end/package-lock.json
  back-end/package.json
  back-end/src/api/app.js
  back-end/src/controller/index.js
  back-end/src/controller/loginController.js
  back-end/src/controller/userController.js
  back-end/src/database/config/config.js
  back-end/src/database/migrations/20211110000658-create-users.js
  back-end/src/database/migrations/20211110001044-create-products.js
  back-end/src/database/migrations/20211110001208-create-sales.js
  back-end/src/database/migrations/20211110001353-create-sales-products.js
  back-end/src/database/models/products.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/salesproducts.js
  back-end/src/database/models/users.js
  back-end/src/database/seeders/20211111140748-users.js
  back-end/src/database/seeders/20211111141339-products.js
  back-end/src/routes/index.js
  back-end/src/routes/loginRouter.js
  back-end/src/routes/userRouter.js
  back-end/src/service/index.js
  back-end/src/service/loginService.js
  back-end/src/service/userService.js
  package-lock.json
Labels: code review

#110 [Group 6] - Register BackEnd Creation
  back-end/package-lock.json
  back-end/package.json
  back-end/src/api/app.js
  back-end/src/api/server.js
  back-end/src/controllers/registerController.js
  back-end/src/middlewares/registerValidations.js
  back-end/src/routers/registerRouter.js
  package-lock.json
Labels: group-06

#124 Main group 8 tantofaz
  back-end/src/controllers/user.js
  back-end/src/database/migrations/20211109211240-users.js
  back-end/src/database/migrations/20211109211642-sales.js
  back-end/src/database/migrations/20211109212050-products.js
  back-end/src/database/migrations/20211109212352-salesProducts.js
  back-end/src/database/models/product.js
  back-end/src/database/models/sale.js
  back-end/src/database/models/saleProduct.js
  back-end/src/database/models/user.js
  back-end/src/database/seeders/20211109220036-Users.js
  back-end/src/database/seeders/20211109221215-Products.js
  back-end/src/models/Products.js
  back-end/src/models/User.js
  back-end/src/services/User.js
  back-end/src/validations/validations.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/pages/Login.js
  package-lock.json
Labels: group-8

#127 Main group 3 backend admin
  back-end/src/api/app.js
  back-end/src/api/auth/validateToken.js
  back-end/src/api/controllers/userController.js
  back-end/src/api/messages/errorMessages.js
  back-end/src/api/middleware/validateAdmin.js
  back-end/src/api/middleware/validateNewUser.js
  back-end/src/api/services/userService.js
Labels: group-03

#105 Get products route
  back-end/public/images/antarctica_pilsen_300ml.jpg
  back-end/public/images/becks_330ml.jpg
  back-end/public/images/becks_600ml.jpg
  back-end/public/images/brahma_600ml.jpg
  back-end/public/images/brahma_duplo_malte_350ml.jpg
  back-end/public/images/da_mantiqueira_red_ale.jpg
  back-end/public/images/heineken_600ml.jpg
  back-end/public/images/images.zip
  back-end/public/images/skol_269ml.jpg
  back-end/public/images/skol_beats_senses_269ml.jpg
  back-end/public/images/skol_beats_senses_313ml.jpg
  back-end/public/images/skol_lata_350ml.jpg
  back-end/public/images/stella_artois_275ml.jpg
  back-end/src/api/app.js
  back-end/src/api/controllers/productController.js
  back-end/src/api/services/productService.js
Labels: grupo-16

#140 [MAIN GROUP 4] [API] [FEAT] [PersonFlowAdministrator-backEnd-endpoint-createUser]
  back-end/package-lock.json
  back-end/src/api/app.js
  back-end/src/controllers/User/createUser.js
  back-end/src/controllers/User/index.js
  back-end/src/database/migrations/20211110120406-create-user.js
  back-end/src/database/models/user.js
  back-end/src/routes/index.js
  back-end/src/routes/userRoutes.js
  back-end/src/schemas/User/isUserExists.js
  back-end/src/schemas/index.js
Labels: code review

#141 Main group 18 - Configuracao Front End - Login Page
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/pages/Login.jsx
Labels: Group-18

#51 [Group 6] [Front-End] [Login Screen]
  back-end/package-lock.json
  back-end/src/api/app.js
  back-end/src/database/migrations/20211109212337-create-users.js
  back-end/src/database/migrations/20211109212620-create-products.js
  back-end/src/database/migrations/20211109212703-create-sales.js
  back-end/src/database/migrations/20211109212748-create-sales-products.js
  back-end/src/database/models/Product.js
  back-end/src/database/models/Sale.js
  back-end/src/database/models/SaleProduct.js
  back-end/src/database/models/User.js
  back-end/src/database/seeders/20211109221058-seed-users.js
  back-end/src/database/seeders/20211109221111-seed-products.js
  front-end/.eslintrc.json
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/context/ProviderLogin.js
  front-end/src/screens/AdminManage.jsx
  front-end/src/screens/CustomerCheckout.jsx
  front-end/src/screens/CustomerOrders.jsx
  front-end/src/screens/CustomerOrdersDetails.jsx
  front-end/src/screens/CustomerProducts.jsx
  front-end/src/screens/Login.jsx
  front-end/src/screens/SellerOrders.jsx
  front-end/src/screens/SellerOrdersDetails.jsx
  package-lock.json
  package.json
Labels: group-06

#117 Main group 16 register screen
  back-end/package-lock.json
  back-end/src/api/app.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/ultility.js
  front-end/src/pages/Register.js
  front-end/src/redux/slices/userSlice.js
  front-end/src/redux/store/index.js
Labels: grupo-16

#163 [Group 13] - Add sell to Database
  back-end/src/controllers/productController.js
  back-end/src/middlewares/index.js
  back-end/src/middlewares/validateToken.js
  back-end/src/routers/productRouter.js
  back-end/src/services/productService.js
  back-end/src/services/userService.js
  back-end/src/utils/errorMap.js
Labels: code review

#180 [Maingroup 13] - Socket.io
  back-end/src/api/app.js
  back-end/src/api/server.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/LoginForm.jsx
  front-end/src/context/Provider.js
Labels: code review

#152 Login
  __tests__/end-to-end/actions/common/navigate.js
  back-end/src/api/server.js
  back-end/src/controllers/User.js
  back-end/src/database/models/saleProduct.js
  back-end/src/models/User.js
  back-end/src/services/User.js
  back-end/src/sockets/login.js
  front-end/src/pages/Login.js
  package-lock.json
  package.json
Labels: group-8

#147 [Group 6] Create register screen
  front-end/package-lock.json
  front-end/src/context/ProviderLogin.js
  front-end/src/screens/SingUp.jsx
  front-end/src/utils/validateRegisterInputs.js
Labels: group-06

#144 Main group 3 authorization
  back-end/src/api/app.js
  back-end/src/api/middleware/index.js
  back-end/src/api/services/userService.js
  back-end/src/database/migrations/20211109180427-create-user.js
  back-end/src/database/migrations/20211109185711-create-sales.js
  back-end/src/database/models/user.js
  back-end/src/database/seeders/20211109203203-users.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/components/NavBar.jsx
  front-end/src/components/ProductsList.jsx
  front-end/src/contexts/Login.js
  front-end/src/contexts/Products.js
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/pages/Login.jsx
  front-end/src/pages/Products.jsx
  package-lock.json
  package.json
Labels: group-03

#120 Login Back-end
  back-end/package-lock.json
  back-end/package.json
  back-end/src/api/app.js
  back-end/src/api/controllers/loginController.js
  back-end/src/api/middlewares/loginValidationMid.js
  back-end/src/api/schemas/userValidation.js
  back-end/src/api/services/loginService.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/sales_products.js
  back-end/src/database/models/users.js
  back-end/src/database/seeders/20211110190345-users.js
Labels: group-14

#131 [ Group 14 ] Login Frontend
  README.md
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/index.js
  front-end/src/pages/Login.jsx
  front-end/src/redux/store.js
  front-end/src/redux/userSlice.js
Labels: group-14

#94 [Main Group 16] Customer Products
  README.md
  back-end/package-lock.json
  back-end/src/api/app.js
  front-end/package-lock.json
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/components/CartCard.js
  front-end/src/components/Error.js
  front-end/src/components/NavBar.js
  front-end/src/components/ProductCard.js
  front-end/src/components/ultility.js
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/pages/CustomerCheckout.js
  front-end/src/pages/CustomerProducts.js
  front-end/src/pages/Login.js
  front-end/src/redux/slices/productSlice.js
  front-end/src/redux/slices/userSlice.js
  front-end/src/redux/store/index.js
Labels: grupo-16

#56 [GRUPO 10] (Front-end) Tela de Login
  back-end/.env.example
  back-end/package-lock.json
  back-end/src/api/app.js
  front-end/package-lock.json
  front-end/package.json
  front-end/public/logo-compact.svg
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/App.scss
  front-end/src/Routes.jsx
  front-end/src/components/Alert.jsx
  front-end/src/hooks/useAlert.js
  front-end/src/hooks/useInputs.js
  front-end/src/images/background.png
  front-end/src/images/man-holding-beer.png
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/pages/Auth.jsx
  front-end/src/schemas/login.js
  front-end/src/services/api.js
  front-end/src/styles/components/Alert.module.scss
  front-end/src/styles/pages/Auth.module.scss
Labels: code review

#2 main-group-11 - Login
  back-end/package-lock.json
  back-end/package.json
  back-end/src/api/app.js
  back-end/src/api/routes/login.js
  back-end/src/api/services/user.js
  back-end/src/database/migrations/20211109162427-create-user.js
  back-end/src/database/migrations/20211109162540-create-sale.js
  back-end/src/database/migrations/20211109162552-create-product.js
  back-end/src/database/migrations/20211109162620-create-products-sale.js
  back-end/src/database/models/index.js
  back-end/src/database/models/product.js
  back-end/src/database/models/productsSale.js
  back-end/src/database/models/sale.js
  back-end/src/database/models/user.js
  back-end/src/database/schemas/productsSale.js
  back-end/src/database/schemas/sale.js
  back-end/src/database/schemas/user.js
  back-end/src/database/seeders/20211109174234-seed-users.js
  back-end/src/database/seeders/20211109174319-seed-products.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/atoms/Button.jsx
  front-end/src/components/atoms/ErrorMessage.jsx
  front-end/src/components/atoms/Input.jsx
  front-end/src/components/molecules/LoginForm.jsx
  front-end/src/context/Products/ProductsContext.jsx
  front-end/src/context/Sales/SalesContext.jsx
  front-end/src/context/Users/UsersContext.jsx
  front-end/src/context/Users/UsersProvider.jsx
  front-end/src/routes/routes.jsx
  front-end/src/utils/validations/API/fetch.js
  front-end/src/utils/validations/joi/login.js
  front-end/src/utils/validations/validateEmail.js
  front-end/src/utils/validations/validatePassword.js
Labels: group-11

#168 Main group 8 feat tela de produtos
  back-end/public/antarctica_pilsen_300ml.jpg
  back-end/public/becks_330ml.jpg
  back-end/public/becks_600ml.jpg
  back-end/public/brahma_600ml.jpg
  back-end/public/brahma_duplo_malte_350ml.jpg
  back-end/public/da_mantiqueira_red_ale.jpg
  back-end/public/heineken_600ml.jpg
  back-end/public/skol_269ml.jpg
  back-end/public/skol_beats_senses_269ml.jpg
  back-end/public/skol_beats_senses_313ml.jpg
  back-end/public/skol_lata_350ml.jpg
  back-end/public/stella_artois_275ml.jpg
  back-end/src/api/server.js
  back-end/src/database/migrations/20211109212050-products.js
  back-end/src/database/models/product.js
  back-end/src/database/seeders/20211109221215-Products.js
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/components/CardProducts.js
  front-end/src/components/NavBar.js
  front-end/src/pages/Products.js
  front-end/src/provider/DeliveryProvider.js
  front-end/src/utils/Data.js
Labels: group-8

#217 [ Main group 3 backend ] - rota sales
  back-end/src/api/app.js
  back-end/src/api/controllers/index.js
  back-end/src/api/controllers/saleController.js
  back-end/src/api/controllers/userController.js
  back-end/src/api/services/index.js
  back-end/src/api/services/saleService.js
  back-end/src/api/services/userService.js
  back-end/src/database/migrations/20211109184609-create-products.js
  back-end/src/database/migrations/20211109185711-create-sales.js
  back-end/src/database/migrations/20211109191743-create-sales-products.js
  back-end/src/database/models/products.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/salesproducts.js
Labels: group-03

#228 [GRUPO 10] (Front-end) Restauração de requisitos
  back-end/package-lock.json
  front-end/package-lock.json
  front-end/src/App.scss
  package-lock.json
Labels: Grupo 10

#233 [GRUPO 10] (Front-end) Barra de navegação
  README.md
  back-end/package-lock.json
  front-end/package-lock.json
  front-end/package.json
  front-end/public/logo.svg
  front-end/src/App.js
  front-end/src/App.scss
  front-end/src/components/NavBar.jsx
  front-end/src/contexts/auth.js
  front-end/src/index.js
  front-end/src/pages/Auth.jsx
  front-end/src/styles/components/NavBar.module.scss
  front-end/src/styles/pages/Auth.module.scss
  package-lock.json
Labels: Grupo 10

#236 [Group 14] register user back
  back-end/src/api/app.js
  back-end/src/api/controllers/loginController.js
  back-end/src/api/controllers/userController.js
  back-end/src/api/middlewares/registerValidationMid.js
  back-end/src/api/schemas/userValidation.js
  back-end/src/api/services/loginService.js
  back-end/src/api/services/userService.js
  back-end/src/tests/userController.test.js
  front-end/package-lock.json
Labels: code review, group-14

#145 [Grupo 10] (Back-end) Fluxo clientes
  back-end/jwt.evaluation.key
  back-end/src/api/app.js
  back-end/src/controller/index.js
  back-end/src/controller/loginController.js
  back-end/src/controller/productControllers.js
  back-end/src/controller/saleController.js
  back-end/src/database/migrations/20211110001208-create-sales.js
  back-end/src/database/migrations/20211110001353-create-sales-products.js
  back-end/src/database/models/products.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/salesproducts.js
  back-end/src/database/seeders/20211117184545-sales.js
  back-end/src/images/antarctica_pilsen_300ml.jpg
  back-end/src/images/becks_330ml.jpg
  back-end/src/images/becks_600ml.jpg
  back-end/src/images/brahma_600ml.jpg
  back-end/src/images/brahma_duplo_malte_350ml.jpg
  back-end/src/images/da_mantiqueira_red_ale.jpg
  back-end/src/images/heineken_600ml.jpg
  back-end/src/images/skol_269ml.jpg
  back-end/src/images/skol_beats_senses_269ml.jpg
  back-end/src/images/skol_beats_senses_313ml.jpg
  back-end/src/images/skol_lata_350ml.jpg
  back-end/src/images/stella_artois_275ml.jpg
  back-end/src/middleware/auth.js
  back-end/src/middleware/index.js
  back-end/src/middleware/multer.js
  back-end/src/routes/index.js
  back-end/src/routes/productRouter.js
  back-end/src/routes/saleRouter.js
  back-end/src/service/index.js
  back-end/src/service/loginService.js
  back-end/src/service/productService.js
  back-end/src/service/salesService.js
  back-end/src/service/userService.js
Labels: code review, Grupo 10

#254 Main group 8 merging
  back-end/package-lock.json
  back-end/package.json
  back-end/src/api/server.js
  back-end/src/auth/newJWT.js
  back-end/src/auth/validateJwtAdmin.js
  back-end/src/controllers/User.js
  back-end/src/models/User.js
  back-end/src/services/User.js
  front-end/package-lock.json
  front-end/src/App.js
  front-end/src/Components/AdminForm/index.jsx
  front-end/src/Components/CardProducts/index.jsx
  front-end/src/Components/Header/index.jsx
  front-end/src/Components/Table/index.jsx
  front-end/src/Contexts/Deliveries/DeliveryContext.js
  front-end/src/Contexts/Deliveries/DeliveryProvider.js
  front-end/src/Contexts/User/userContext.js
  front-end/src/Contexts/User/userProvider.js
  front-end/src/Routes.js
  front-end/src/components/NavBar.js
  front-end/src/pages/Admin.js
  front-end/src/pages/Checkout.jsx
  front-end/src/pages/Login.js
  front-end/src/pages/Products.js
  front-end/src/utils/Data.js
Labels: group-8

#261 Main group 8 feat tela de produtos
  front-end/src/App.css
  front-end/src/Components/CardProducts/index.jsx
  front-end/src/Components/Header/index.jsx
  front-end/src/pages/Products.js
Labels: group-8

#264 [Main group 3 backend sales] - rota sales
  back-end/src/api/app.js
  back-end/src/api/controllers/saleController.js
  back-end/src/api/messages/errorMessages.js
  back-end/src/api/middleware/validateSeller.js
  back-end/src/api/middleware/validateUpdateOrder.js
  back-end/src/api/services/saleService.js
  back-end/src/database/migrations/20211109185711-create-sales.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/user.js
Labels: group-03

#208 [Main Group 16] Customer Checkout Page
  back-end/src/api/app.js
  back-end/src/api/controllers/saleController.js
  back-end/src/api/services/saleService.js
  back-end/src/database/migrations/20211109191441-create-sales.js
  back-end/src/database/models/sales.js
  front-end/src/components/OrderItemCard.js
  front-end/src/components/ultility.js
  front-end/src/pages/CustomerCheckout.js
  front-end/src/pages/Login.js
  front-end/src/redux/slices/productSlice.js
  front-end/src/redux/slices/userSlice.js
Labels: grupo-16

#231 Main group 6 backend checkout
  back-end/package-lock.json
  back-end/src/api/app.js
  back-end/src/controllers/salesController.js
  back-end/src/database/migrations/20211109212620-create-products.js
  back-end/src/database/migrations/20211109212703-create-sales.js
  back-end/src/database/migrations/20211109212748-create-sales-products.js
  back-end/src/database/models/Product.js
  back-end/src/database/models/Sale.js
  back-end/src/database/models/SaleProduct.js
  back-end/src/database/models/User.js
  back-end/src/middlewares/saleValidations.js
  back-end/src/routers/salesRouter.js
  back-end/src/services/salesService.js
  back-end/src/tests/createSale.test.js
  front-end/package-lock.json
Labels: group-06

#268 [Main group 16] [rotas backend]
  back-end/src/api/Routes/index.js
  back-end/src/api/Routes/routes.js
  back-end/src/api/app.js
  back-end/src/api/controllers/saleController.js
  back-end/src/api/controllers/userController.js
  back-end/src/api/services/saleService.js
Labels: grupo-16

#267 [Group 6] Customer flow frontend
  back-end/public/images/antarctica_pilsen_300ml.jpg
  back-end/public/images/becks_330ml.jpg
  back-end/public/images/becks_600ml.jpg
  back-end/public/images/brahma_600ml.jpg
  back-end/public/images/brahma_duplo_malte_350ml.jpg
  back-end/public/images/da_mantiqueira_red_ale.jpg
  back-end/public/images/heineken_600ml.jpg
  back-end/public/images/skol_269ml.jpg
  back-end/public/images/skol_beats_senses_269ml.jpg
  back-end/public/images/skol_beats_senses_313ml.jpg
  back-end/public/images/skol_lata_350ml.jpg
  back-end/public/images/stella_artois_275ml.jpg
  back-end/src/api/app.js
  back-end/src/controllers/loginController.js
  back-end/src/controllers/productController.js
  back-end/src/routers/productRouter.js
  front-end/src/App.js
  front-end/src/components/NavBar.jsx
  front-end/src/components/ProductCard.jsx
  front-end/src/context/ContextProducts.js
  front-end/src/context/ProviderLogin.js
  front-end/src/context/ProviderProducts.js
  front-end/src/screens/CustomerProducts.jsx
  front-end/src/utils/LocalStorageFunctions.js
Labels: group-06

#257 [ grupo 10] Tela de registro - estilização e melhor componentização
  front-end/src/App.js
  front-end/src/Routes.jsx
  front-end/src/components/registerForm.jsx
  front-end/src/pages/RegisterPage.jsx
  front-end/src/styles/components/RegisterForm.scss
  front-end/src/styles/pages/Register.module.scss
Labels: Grupo 10

#278 [GROUP 13] - back socket
  back-end/package-lock.json
  back-end/src/api/app.js
  back-end/src/sockets/index.js
  front-end/package-lock.json
  front-end/src/components/productCard.jsx
  front-end/src/context/Provider.js
Labels: code review

#286 Main group 8 feat tela de produtos
  back-end/src/api/server.js
  back-end/src/auth/validateToken.js
  front-end/src/Components/CardProducts/index.jsx
  front-end/src/Components/Header/index.jsx
  front-end/src/Contexts/Deliveries/DeliveryProvider.js
  front-end/src/Contexts/User/userProvider.js
  front-end/src/pages/Login.js
  front-end/src/pages/Products.js
  front-end/src/utils/Data.js
Labels: group-8

#296 [Group 14] Lista de produtos
  back-end/package-lock.json
  back-end/src/api/app.js
  back-end/src/api/controllers/productController.js
  back-end/src/api/images/antarctica_pilsen_300ml.jpg
  back-end/src/api/images/becks_330ml.jpg
  back-end/src/api/images/becks_600ml.jpg
  back-end/src/api/images/brahma_600ml.jpg
  back-end/src/api/images/brahma_duplo_malte_350ml.jpg
  back-end/src/api/images/da_mantiqueira_red_ale.jpg
  back-end/src/api/images/heineken_600ml.jpg
  back-end/src/api/images/skol_269ml.jpg
  back-end/src/api/images/skol_beats_senses_269ml.jpg
  back-end/src/api/images/skol_beats_senses_313ml.jpg
  back-end/src/api/images/skol_lata_350ml.jpg
  back-end/src/api/images/stella_artois_275ml.jpg
  back-end/src/api/middlewares/authMid.js
  back-end/src/api/middlewares/loginValidationMid.js
  back-end/src/api/schemas/userValidation.js
  back-end/src/api/services/productService.js
  back-end/src/api/services/userService.js
  front-end/.eslintignore
  front-end/.stylelintignore
  front-end/package-lock.json
  front-end/package.json
  front-end/postcss.config.js
  front-end/src/App.js
  front-end/src/components/NavBar.jsx
  front-end/src/components/ProductCard.jsx
  front-end/src/components/ProductList.jsx
  front-end/src/index.js
  front-end/src/pages/Customer.jsx
  front-end/src/pages/Login.jsx
  front-end/src/redux/userSlice.js
  front-end/src/style/main.css
  front-end/src/style/tailwind.css
  front-end/tailwind.config.js
  package-lock.json
Labels: group-14

#273 [ Group 14 ] Login sem conflito (espero eu)
  back-end/package-lock.json
  back-end/src/api/middlewares/loginValidationMid.js
  back-end/src/api/schemas/userValidation.js
  front-end/.eslintignore
  front-end/.stylelintignore
  front-end/package-lock.json
  front-end/package.json
  front-end/postcss.config.js
  front-end/src/index.js
  front-end/src/pages/Login.jsx
  front-end/src/redux/userSlice.js
  front-end/src/style/main.css
  front-end/src/style/tailwind.css
  front-end/tailwind.config.js
  package-lock.json
Labels: group-14

#280 [GRUPO 10] (Front-end) Contexto de autenticação
  back-end/jwt.evaluation.key
  front-end/src/Routes.jsx
  front-end/src/Routes/ProtectedRoute.jsx
  front-end/src/Routes/index.jsx
  front-end/src/components/LoginForm.jsx
  front-end/src/components/NavBar.jsx
  front-end/src/components/RegisterForm.jsx
  front-end/src/components/registerForm.jsx
  front-end/src/contexts/auth.js
  front-end/src/hooks/useAuth.js
  front-end/src/pages/Auth.jsx
  front-end/src/pages/RegisterPage.jsx
Labels: code review, Grupo 10

#301 [main-group-17] Tela pessoa administradora
  back-end/src/api/controllers/user.js
  back-end/src/api/middlewares/validateData.js
  back-end/src/api/services/user.js
  front-end/src/App.js
  front-end/src/components/AdminForm/index.jsx
  front-end/src/components/AdminForm/styles.module.css
  front-end/src/components/AdminUserList/index.jsx
  front-end/src/components/Header/index.jsx
  front-end/src/components/LoginForm/index.jsx
  front-end/src/components/RegisterForm/index.jsx
  front-end/src/pages/AdminPage/index.jsx
  front-end/src/pages/AdminPage/styles.module.css
  front-end/src/services/adminRegister/adminRegister.js
  front-end/src/services/getUsersFromServer/getAllUsers.js
  front-end/src/services/loginAndRegister/postRequest.js
  front-end/src/services/loginAndRegister/validations.js
  front-end/src/utils/endPointsData.js
  front-end/src/utils/statusCodes.js
Labels: group-17

#255 inicando a componetização da aplicação
  back-end/src/api/app.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/components/Header/Header.jsx
  front-end/src/components/Header/HeaderElements.jsx
  front-end/src/index.js
  front-end/src/pages/Cadastro.jsx
  front-end/src/pages/TodosOsPedidos.jsx
  front-end/src/pages/generalStyles.jsx
Labels: Group-18

#312 [Group 6] [Feat] [Admin Screen]
  back-end/src/middlewares/validateJwt.js
  back-end/src/routers/registerRouter.js
  front-end/src/components/CreateUser.jsx
  front-end/src/components/NavBarAdmin.jsx
  front-end/src/context/ProviderLogin.js
  front-end/src/screens/AdminManage.jsx
  front-end/src/screens/Login.jsx
Labels: group-06

#199 [Group 6] [Feat] [CustomerCheckout]
  back-end/package-lock.json
  back-end/src/api/app.js
  back-end/src/controllers/loginController.js
  back-end/src/controllers/salesController.js
  back-end/src/controllers/usersController.js
  back-end/src/database/migrations/20211109212703-create-sales.js
  back-end/src/database/migrations/20211109212748-create-sales-products.js
  back-end/src/database/models/Sale.js
  back-end/src/routers/usersRouter.js
  back-end/src/services/salesService.js
  back-end/src/services/usersService.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/DeliveryDetails.jsx
  front-end/src/components/DropDown.jsx
  front-end/src/components/Input.jsx
  front-end/src/components/ProductsCheckoutTable.jsx
  front-end/src/context/ProviderProducts.js
  front-end/src/screens/CustomerCheckout.jsx
  front-end/src/screens/CustomerProducts.jsx
Labels: group-06

#320 Group 14 - Listagem de produtos
  back-end/src/api/middlewares/authMid.js
  back-end/src/api/services/userService.js
  back-end/src/database/migrations/20211110174601-create-products.js
  data-testids.md
  front-end/src/components/NavBar.jsx
  front-end/src/components/ProductCard.jsx
  front-end/src/components/ProductList.jsx
  front-end/src/pages/Customer.jsx
  front-end/src/redux/cartSlice.js
  front-end/src/redux/store.js
Labels: code review, group-14

#335 Main group 6 create register test
  back-end/package-lock.json
  back-end/package.json
  back-end/src/middlewares/loginValidations.js
  back-end/src/tests/createSale.test.js
  back-end/src/tests/loginUser.test.js
  back-end/src/tests/registerUser.test.js
  back-end/src/utils/errorMessages.js
  front-end/package-lock.json
  package-lock.json
Labels: group-06

#298 feat: creation of login tests
  back-end/package-lock.json
  back-end/package.json
  back-end/src/api/app.js
  back-end/src/middlewares/loginValidations.js
  back-end/src/tests/createSale.test.js
  back-end/src/tests/login.test.js
  back-end/src/utils/errorMessages.js
Labels: group-06

#344 Main group 6 products tests creation
  back-end/src/tests/products.test.js
  back-end/src/tests/registerUser.test.js
Labels: group-06

#266 Main group 3 new register
  back-end/package-lock.json
  back-end/src/database/config/config.js
  front-end/package-lock.json
  front-end/src/App.js
  front-end/src/contexts/Register.js
  front-end/src/pages/Login.jsx
  front-end/src/pages/Products.jsx
  front-end/src/pages/Register.js
  package-lock.json
Labels: group-03

#292 [GRUPO 01] Feat: REQ 44 - Cria botao de remover usuarios
  back-end/src/api/app.js
  back-end/src/controllers/UserController.js
  back-end/src/middlewares/validations.js
  back-end/src/services/userService.js
  front-end/src/App.js
  front-end/src/components/CustomerNavBar.jsx
  front-end/src/components/UserList.jsx
  front-end/src/contexts/UsersContext.js
  front-end/src/contexts/UsersProvider.jsx
  front-end/src/pages/AdmPage.jsx
  front-end/src/pages/Login.jsx
Labels: code review

#212 Main group 3 frontend admin page
  back-end/src/api/app.js
  back-end/src/api/auth/validateToken.js
  back-end/src/api/controllers/userController.js
  back-end/src/api/services/userService.js
  front-end/src/App.js
  front-end/src/components/NavBar.jsx
  front-end/src/components/UserForm.jsx
  front-end/src/components/UsersTable.jsx
  front-end/src/contexts/Users.js
  front-end/src/pages/Admin.jsx
  front-end/src/pages/Login.jsx
Labels: group-03

#314 [ Main group 18 customer orders ]
  back-end/src/api/app.js
  back-end/src/api/controller/sales.js
  back-end/src/api/controller/users.js
  back-end/src/api/validations/schema.js
  back-end/src/database/models/sale.js
  back-end/src/database/models/sales_product.js
  front-end/package-lock.json
  front-end/src/App.js
  front-end/src/components/bottomBox.jsx
  front-end/src/components/header.jsx
  front-end/src/components/productCard.jsx
  front-end/src/components/salesCard.jsx
  front-end/src/pages/Produtos.jsx
  front-end/src/pages/TodosOsPedidos.jsx
Labels: code review

#306 Main group 8 backend add sale
  back-end/package-lock.json
  back-end/src/api/server.js
  back-end/src/auth/validateGeneric.js
  back-end/src/controllers/Sales.js
  back-end/src/controllers/User.js
  back-end/src/database/migrations/20211109211642-sales.js
  back-end/src/database/migrations/20211109212352-salesProducts.js
  back-end/src/database/models/sale.js
  back-end/src/database/models/saleProduct.js
  back-end/src/models/Sales.js
  back-end/src/models/User.js
  back-end/src/services/Sales.js
  back-end/src/services/User.js
  front-end/src/Components/CardProducts/index.jsx
  front-end/src/Components/Table/index.jsx
  front-end/src/Contexts/User/userProvider.js
  front-end/src/Routes.js
  front-end/src/pages/Checkout/helpers.js
  front-end/src/pages/Checkout/index.js
  front-end/src/pages/Products.js
  front-end/src/pages/SignUp.js
  front-end/src/pages/orders.js
Labels: group-8

#234 [GRUPO 10] (Front-end) Tela de Produtos
  front-end/package-lock.json
  front-end/package.json
  front-end/public/index.html
  front-end/src/App.js
  front-end/src/App.scss
  front-end/src/Routes/index.jsx
  front-end/src/components/ProductCard.jsx
  front-end/src/contexts/cart.js
  front-end/src/images/noimage.jpg
  front-end/src/index.js
  front-end/src/pages/customer/Products.jsx
  front-end/src/styles/components/ProductCard.module.scss
  front-end/src/styles/pages/Products.module.scss
Labels: code review, Grupo 10

#392 [Main Group 17] Fix requisito 22 23 24
  front-end/src/components/RequestCard/index.jsx
  front-end/src/components/RequestCard/styles.module.css
  front-end/src/utils/dataTestIdsMyRequestPage.js
  front-end/src/utils/formatDate.js
Labels: group-17

#390 Main group 6 create order screen
  back-end/package-lock.json
  back-end/src/api/server.js
  back-end/src/controllers/salesController.js
  back-end/src/database/seeders/20211109221058-seed-users.js
  back-end/src/middlewares/validateJwt.js
  back-end/src/routers/salesRouter.js
  back-end/src/services/salesService.js
  back-end/src/sockets/socketStatus.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/CreateUser.jsx
  front-end/src/components/NavBar.jsx
  front-end/src/components/NavBarAdmin.jsx
  front-end/src/components/OrderCard.jsx
  front-end/src/components/ProductCard.jsx
  front-end/src/components/StatusCard.jsx
  front-end/src/context/ProviderProducts.js
  front-end/src/screens/CustomerOrders.jsx
  front-end/src/screens/CustomerProducts.jsx
  front-end/src/screens/Login.jsx
  front-end/src/utils/convertDateFormat.js
  front-end/src/utils/getServerUrl.js
Labels: group-06

#359 Main group 3 customer products
  back-end/public/images/antarctica_pilsen_300ml.jpg
  back-end/public/images/becks_330ml.jpg
  back-end/public/images/becks_600ml.jpg
  back-end/public/images/brahma_600ml.jpg
  back-end/public/images/brahma_duplo_malte_350ml.jpg
  back-end/public/images/da_mantiqueira_red_ale.jpg
  back-end/public/images/heineken_600ml.jpg
  back-end/public/images/skol_269ml.jpg
  back-end/public/images/skol_beats_senses_269ml.jpg
  back-end/public/images/skol_beats_senses_313ml.jpg
  back-end/public/images/skol_lata_350ml.jpg
  back-end/public/images/stella_artois_275ml.jpg
  back-end/src/api/app.js
  back-end/src/api/auth/validateToken.js
  back-end/src/api/controllers/userController.js
  back-end/src/database/migrations/20211109184609-create-products.js
  back-end/src/database/migrations/20211109191743-create-sales-products.js
  back-end/src/database/models/products.js
  back-end/src/database/seeders/20211109204407-products.js
  front-end/src/App.js
  front-end/src/components/ButtonLogout.jsx
  front-end/src/components/NavBar.jsx
  front-end/src/components/ProductCard.jsx
  front-end/src/components/ProductsList.jsx
  front-end/src/contexts/Cart.js
  front-end/src/contexts/Login.js
  front-end/src/pages/Checkout.jsx
  front-end/src/pages/Login.jsx
  front-end/src/pages/Products.jsx
Labels: group-03

#176 [Group 6] [Test] [Login]
  front-end/src/tests/loginTest.test.js
  front-end/src/tests/renderWithRouter.js
Labels: group-06

#355 [Group 6] Order details
  back-end/package-lock.json
  back-end/src/controllers/salesController.js
  back-end/src/routers/salesRouter.js
  front-end/package-lock.json
  front-end/src/components/OrderDetailsDashboard.jsx
  front-end/src/components/ProductInSaleCard.jsx
  front-end/src/screens/CustomerOrdersDetails.jsx
Labels: group-06

#338 [ grupo 10 ] ( front-end ) Tela de administrador
  back-end/src/controller/loginController.js
  front-end/src/Routes/index.jsx
  front-end/src/components/LoginForm.jsx
  front-end/src/components/NavBar.jsx
  front-end/src/components/admForm/admForm.jsx
  front-end/src/contexts/auth.js
  front-end/src/hooks/useAuth.js
  front-end/src/pages/AdminPage.jsx
  front-end/src/pages/Auth.jsx
  front-end/src/schemas/register.js
  package-lock.json
  package.json
Labels: Grupo 10

#419 [Main Group 17] Tela de Detalhes da venda
  back-end/src/api/app.js
  back-end/src/api/controllers/sales.js
  back-end/src/api/router/saleRouter.js
  back-end/src/api/services/sales.js
  front-end/src/components/OrderDetails/index.jsx
  front-end/src/components/OrderDetails/styles.module.css
  front-end/src/pages/ClientOrderDetailsPage/index.jsx
  front-end/src/pages/MyRequestsPage/index.jsx
  front-end/src/utils/dataTestIds.js
Labels: group-17

#432 [GROUP - 13] - RedirectByRole
  __tests__/end-to-end/04customer_checkout.test.js
  back-end/src/controllers/saleController.js
  back-end/src/routers/customerRouter.js
  back-end/src/services/saleService.js
  back-end/src/utils/errorMap.js
  front-end/src/App.jsx
  front-end/src/components/LoginForm.jsx
  front-end/src/components/SellerOrderCard.jsx
  front-end/src/components/header.jsx
  front-end/src/context/Provider.js
  front-end/src/pages/CheckoutClient.jsx
  front-end/src/pages/SellerOrders.jsx
Labels: code review

#413 [Group 14] customer orders
  back-end/src/api/app.js
  back-end/src/api/controllers/productController.js
  back-end/src/api/controllers/salesController.js
  back-end/src/api/services/productService.js
  back-end/src/api/services/salesService.js
  back-end/src/database/migrations/20211110174745-create-sales-products.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/salesProducts.js
  back-end/src/database/models/users.js
  front-end/src/components/DetailTable.jsx
  front-end/src/components/NavBar.jsx
  front-end/src/components/SaleDetail.jsx
  front-end/src/components/UserOrders.js
  front-end/src/pages/Customer.jsx
  front-end/src/pages/Login.jsx
Labels: code review, group-14

#365 Main group 6 create sales test
  back-end/src/middlewares/registerValidations.js
  back-end/src/middlewares/validateJwt.js
  back-end/src/tests/01loginUser.test.js
  back-end/src/tests/02registerUser.test.js
  back-end/src/tests/03product.test.js
  back-end/src/tests/04sale.test.js
  back-end/src/utils/errorMessages.js
Labels: group-06

#436 fix: tests fixed to correct result on test:coverage
  back-end/src/tests/02registerUser.test.js
  back-end/src/tests/04sale.test.js
  back-end/src/tests/07registerController.test.js
Labels: group-06

#424 [Main group 17] Fix avisos do react ao usar useEffect
  front-end/src/components/Header/index.jsx
  front-end/src/components/ItemCard/index.jsx
  front-end/src/components/ItemCard/styles.module.css
  front-end/src/components/LoginForm/index.jsx
  front-end/src/components/RegisterForm/index.jsx
  front-end/src/pages/ClientOrderDetailsPage/index.jsx
  front-end/src/pages/ProductPage/index.jsx
Labels: group-17

#459 Main group 18 pedido especifico e refatorar backend
  back-end/package.json
  back-end/src/api/controller/sales.js
  front-end/src/API/dataBaseCall.js
  front-end/src/components/Header/Header.jsx
  front-end/src/components/checkoutProduct.jsx
  front-end/src/components/checkoutProduct/checkoutProduct.jsx
  front-end/src/context/checkoutProvider.js
  front-end/src/pages/CheckoutComprador.jsx
  front-end/src/pages/Login/Login.jsx
  front-end/src/pages/Login/localStorage.js
  front-end/src/pages/PedidoEspecífico.jsx
  front-end/src/routes/Routes.jsx
Labels: Group-18

#415 Main group 3 frontend checkout
  back-end/package-lock.json
  back-end/src/api/app.js
  back-end/src/api/auth/validateToken.js
  back-end/src/api/controllers/saleController.js
  back-end/src/api/controllers/userController.js
  back-end/src/api/messages/errorMessages.js
  back-end/src/api/middleware/validateUpdateOrder.js
  back-end/src/api/services/saleService.js
  back-end/src/api/services/userService.js
  back-end/src/database/migrations/20211109180427-create-user.js
  back-end/src/database/migrations/20211109185711-create-sales.js
  back-end/src/database/migrations/20211109191743-create-sales-products.js
  back-end/src/database/models/products.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/salesproducts.js
  back-end/src/database/models/user.js
  front-end/package-lock.json
  front-end/src/components/ButtonRemoveItem.jsx
  front-end/src/components/ButtonTotal.jsx
  front-end/src/components/CheckoutTable.jsx
  front-end/src/components/DeliveryDetails.jsx
  front-end/src/components/NavBar.jsx
  front-end/src/components/OrderItem.jsx
  front-end/src/components/ProductCard.jsx
  front-end/src/contexts/Users.js
  front-end/src/index.js
  front-end/src/pages/Admin.jsx
  front-end/src/pages/Checkout.jsx
  front-end/src/pages/Login.jsx
  front-end/src/pages/Products.jsx
  front-end/src/pages/Register.js
Labels: group-03

#367 [Main Group 16] Order Details Page
  back-end/src/api/app.js
  back-end/src/api/controllers/saleController.js
  back-end/src/api/services/saleService.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/salesProducts.js
  back-end/src/database/models/users.js
  front-end/src/App.js
  front-end/src/components/NavBar.css
  front-end/src/components/NavBar.js
  front-end/src/components/OrderCard.js
  front-end/src/components/OrderDescription.js
  front-end/src/components/Orders.js
  front-end/src/components/ultility.js
  front-end/src/pages/Login.js
  front-end/src/pages/OrderDetails.js
  front-end/src/redux/slices/saleSlice.js
  front-end/src/redux/store/index.js
Labels: grupo-16

#305 [ Group 14 ] Admin Flow (Não finalizado)
  __tests__/end-to-end/07seller_orders.test.js
  back-end/src/api/app.js
  back-end/src/api/controllers/userController.js
  back-end/src/api/middlewares/adminValidationMid.js
  back-end/src/api/services/userService.js
  front-end/src/App.js
  front-end/src/pages/Admin.jsx
Labels: group-14

#455 [Main group 17] styles
  front-end/src/components/OrderDetails/index.jsx
  front-end/src/components/OrderDetails/styles.module.css
  front-end/src/components/RequestCard/index.jsx
  front-end/src/components/RequestCard/styles.module.css
  front-end/src/components/SellerOrderDetails/index.jsx
  front-end/src/components/SellerOrderDetails/styles.module.css
  front-end/src/pages/ClientOrderDetailsPage/styles.module.css
  front-end/src/pages/SellerPage/styles.module.css
Labels: group-17

#470 feat: creation of tests for SingUp.jsx (frontend)
  front-end/src/tests/01login.test.js
  front-end/src/tests/02register.test.js
Labels: group-06

#427 Main group 11 admin manage users
  back-end/src/api/app.js
  back-end/src/api/controllers/user.js
  back-end/src/api/middlewares/checkIfUserExists.js
  back-end/src/api/services/user.js
  front-end/src/components/AdminCreateUser.jsx
  front-end/src/components/AdminUsersList.jsx
  front-end/src/components/molecules/LoginForm.jsx
  front-end/src/datatestids.json
  front-end/src/pages/CustomerOrders.jsx
  front-end/src/pages/Manage.jsx
  front-end/src/pages/Sales.jsx
  front-end/src/pages/SellerOrders.jsx
  front-end/src/routes/routes.jsx
  front-end/src/styles/Manage.css
  front-end/src/utils/API/fetch.js
  front-end/src/utils/validations/joi/adminRegister.js
Labels: group-11

#468 [Group 6] Admin bonus
  back-end/src/controllers/usersController.js
  back-end/src/routers/usersRouter.js
  front-end/src/components/UserItemInList.jsx
  front-end/src/components/UsersList.jsx
  front-end/src/screens/AdminManage.jsx
Labels: group-06

#442 Main group 6 status realtime refresh
  back-end/package-lock.json
  back-end/public/images/antarctica_pilsen_300ml.png
  back-end/public/images/becks_330ml.png
  back-end/public/images/becks_600ml.png
  back-end/public/images/brahma_600ml.png
  back-end/public/images/brahma_duplo_malte_350ml.png
  back-end/public/images/da_mantiqueira_red_ale.png
  back-end/public/images/heineken_600ml.png
  back-end/public/images/skol_269ml.png
  back-end/public/images/skol_beats_senses_269ml.png
  back-end/public/images/skol_beats_senses_313ml.png
  back-end/public/images/skol_lata_350ml.png
  back-end/public/images/stella_artois_275ml.png
  back-end/src/sockets/socketStatus.js
  front-end/package-lock.json
  front-end/src/components/BackgroundContainer.jsx
  front-end/src/components/DeliveryDetails.jsx
  front-end/src/components/NavBar.jsx
  front-end/src/components/NavBarAdmin.jsx
  front-end/src/components/OrderCard.jsx
  front-end/src/components/OrderDetailsDashboard.jsx
  front-end/src/components/SellerOrderTable.jsx
  front-end/src/components/SellerViewOrderCard.jsx
  front-end/src/components/StatusCard.jsx
  front-end/src/index.js
  front-end/src/screens/CustomerOrders.jsx
  front-end/src/screens/CustomerProducts.jsx
  front-end/src/screens/SellerOrdersDetails.jsx
  front-end/src/theme.js
  front-end/src/utils/socketInstance.js
Labels: group-06

#479 Main group 6 tests products front
  front-end/src/tests/01login.test.js
  front-end/src/tests/02register.test.js
  front-end/src/tests/03products.test.js
Labels: group-06

#491 Main group 3 feat customer order details
  back-end/src/api/app.js
  back-end/src/api/auth/validateToken.js
  back-end/src/api/controllers/saleController.js
  back-end/src/api/services/saleService.js
  back-end/src/api/services/userService.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/user.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/components/CheckoutTable.jsx
  front-end/src/components/DeliveryDetails.jsx
  front-end/src/components/OrderCard.jsx
  front-end/src/components/OrderDetailsTable.jsx
  front-end/src/components/UserForm.jsx
  front-end/src/components/orderCard.css
  front-end/src/contexts/Orders.js
  front-end/src/contexts/Users.js
  front-end/src/pages/Admin.jsx
  front-end/src/pages/Login.jsx
  front-end/src/pages/OrderDetails.jsx
  front-end/src/pages/Orders.jsx
  front-end/src/pages/Register.js
Labels: group-03

#499 Main group 17 useshoppincart
  front-end/src/components/Header/index.jsx
  front-end/src/components/Header/styles.module.css
  front-end/src/components/ItemCard/index.jsx
  front-end/src/context/productsProvider.jsx
  front-end/src/hooks/useFetch.jsx
  front-end/src/hooks/useShoppingCart.jsx
  front-end/src/pages/MyRequestsPage/index.jsx
  front-end/src/pages/ProductPage/index.jsx
  front-end/src/pages/SellerPage/index.jsx
  front-end/src/utils/endPointsData.js
Labels: group-17

#422 [MAIN GROUP 4] [FRONT-END] [FEAT] [CARRINHO DE COMPRAS]
  back-end/src/controllers/User/findByEmailUser.js
  back-end/src/controllers/User/getSalesByUser.js
  back-end/src/controllers/User/index.js
  back-end/src/controllers/User/login.js
  back-end/src/controllers/getSalesBySeller.js
  back-end/src/controllers/index.js
  back-end/src/database/migrations/20211110124624-create-product.js
  back-end/src/routes/userRoutes.js
  back-end/src/services/find.js
  back-end/src/services/tokenPassword.js
  front-end/src/components/CardProduto/AddItem.jsx
  front-end/src/components/CardProduto/PrecoProduto.jsx
  front-end/src/components/CardProduto/QuantidadeItens.jsx
  front-end/src/components/CardProduto/RmItem.jsx
  front-end/src/components/LoginForm.jsx
  front-end/src/components/NavBar/LinkLogout.jsx
  front-end/src/components/NavBar/LinkOrders.jsx
  front-end/src/components/NavBar/LinkProducts.jsx
  front-end/src/components/NavBar/NavBar.jsx
  front-end/src/components/NavBar/UserFullName.jsx
  front-end/src/components/SalesList.jsx
  front-end/src/provider/ProductsProvider.js
  front-end/src/services/fetchPostUser.js
  front-end/src/utils/redirectRoutes.js
  front-end/src/validations/loginValidation.js
Labels: group-4, In Progress

#503 [Main group 4] [Front] register
  front-end/src/components/Cadastro.jsx
Labels: group-4, In Progress

#497 Main group 14 seller frontend
  front-end/src/App.js
  front-end/src/components/SaleCard.jsx
  front-end/src/components/SalesList.jsx
  front-end/src/components/SalesOrderList.jsx
  front-end/src/pages/Seller.jsx
  front-end/src/pages/SellerOrderDetails.jsx
Labels: bug, In Progress

#498 main-group-6-fix-req-44
  front-end/src/components/OrderCard.jsx
  front-end/src/components/ProductCard.jsx
  front-end/src/components/StatusCard.jsx
  front-end/src/components/UserItemInList.jsx
  front-end/src/components/UsersList.jsx
  front-end/src/screens/CustomerOrders.jsx
Labels: group-06

#508 [Main group 4] [FRONT] [BACK] olha a tela de register saindo meu polvo
  back-end/src/controllers/User/createUser.js
  front-end/src/components/Cadastro.jsx
  front-end/src/validations/registerValidation.js
Labels: code review
